export { default as Navbar } from './Navbar/Navbar.jsx'
export { default as Description } from './Description/Description.jsx'
export { default as ContactForm } from './Form/ContactForm.jsx'
export { default as Intro } from './Intro/Intro.jsx'
export { default as Footer } from './Footer/Footer.jsx'
